---
- name: Add in memory host
  hosts: localhost
  tasks:
    - name: Add undercloud to in-memory inventory
      add_host:
         name="tester"
         hostname="{{ install.host.ip }}"
         groups="all,undercloud,tester,local"
         ansible_ssh_host="{{ install.host.ip }}"
         ansible_fqdn="{{ install.host.ip }}"
         ansible_ssh_user="{{ install.host.username }}"
         ansible_ssh_private_key_file="{{ install.host.key_file }}"


- name: Patch and repackage components RPM
  hosts: tester
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: patch_rpm }

