---
- name: add hosts to host list
  hosts: localhost
  gather_facts: no
  tasks:
     - name: add each host
       add_host:
          name: "tester"
          groups: "undercloud"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Install python3 on RHEL8 machines
  hosts: undercloud:tester
  gather_facts: no
  tasks:
  - name: This block is required to make facts gathering to work on RHEL8
    block:
      - name: Install python3 with dnf - works on RHEL8
        become: yes
        dnf:
          name:
            - 'python3-devel'
          state: present
        tags: skip_ansible_lint
        ignore_errors: yes


- name: Patch and repackage components RPM
  hosts: undercloud:tester
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: copy_component }
    - { role: patch_rpm }
