---
- name: add hosts to host list
  hosts: localhost
  gather_facts: no
  tasks:
     - add_host:
          name: "controller-0"
          groups: "undercloud"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Run patch-components
  hosts: undercloud
  tasks:
      - name: Setting up repositories
        include_role:
            name: setup_repos

      - name: Setting up the environment
        include_role:
            name: setup_environment
        when: not install.ovs.build|default(false)

      - name: Create a new RPM from a given repository
        include_role:
            name: patch_rpm
        when: not install.ovs.build|default(false)

      - name: Create openvswitch RPMs from ovs source code
        include_role:
            name: build_ovs
        when: install.ovs.build|default(false)