---
- name: add hosts to run the code using ansible-playbook
  hosts: localhost
  gather_facts: no
  tasks:
     - name: add the patcher host to the tester group
       add_host:
          name: "patcher"
          groups: "tester"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Patch and repackage components RPM
  hosts: "{{ install.pattern | default('tester') }}"
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: copy_component }
    - { role: patch_rpm }

- name: Create tmp directory on a local node
  hosts: localhost
  tasks:
    - name: Create tmp dir
      tempfile:
        state: directory
        suffix: "{{ ansible_date_time.iso8601 }}"
      register: tempdir_1

- name: Copy RPMs from to local node
  hosts: "{{ install.pattern | default('tester') }}"
  become: yes
  tasks:
    - name: copy RPMs
      synchronize:
        src: "/patched_rpms"
        dest: "{{ tempdir_1.path }}"
        mode: push

- name: Update undercloud node
  hosts: undercloud
  become: yes
  tasks:
    - name: Setup repository in /etc/yum.repos.d
      template:
        src='patched_rpms.j2'
        dest='/etc/yum.repos.d/patched_rpms.repo'
      tags: patched-rpms-repo

    - name: Copy RPMs to the undercloud if created on an another node
      tags: sync-pull
      synchronize:
        src: "{{ tempdir_1.path }}"
        dest: "/patched_rpms"
        mode: pull

- name: Cleanup
  hosts: localhost
  tasks:
    - name: remove the temporary dir
      file:
        path: "{{ tempdir_1.path }}"
        state: absent
      when: tempfile_1.path is defined

