---
- name: add hosts to host list
  hosts: localhost
  gather_facts: no
  tasks:
     - name: add each host
       add_host:
          name: "tester"
          groups: "undercloud"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Install python3 on RHEL8
  hosts: undercloud:tester
  become: yes
  yum:
    name:
      - 'python3-devel'
      - 'python3-tox'
      - 'python3-testrepository'
      - 'python3-pip'
      - 'python3-py'
      - 'python3-virtualenv'
      - 'python3-pluggy'
    state: present
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int == 8

- name: Patch and repackage components RPM
  hosts: undercloud:tester
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: copy_component }
    - { role: patch_rpm }
