---
- name: Set tester node
  hosts: localhost
  tasks:
    # TODO: change groups.tester to groups.tester|first when Ansible will be updated to at least 2.8.0 as there is a bug in ansible < 2.8.0
    # where groups.tester|first causing 'name' value to evaluate groups.tester even if groups.undercloud is defined
    - name: Add chosen node to tester group
      add_host:
          name: "{{ install.get('tester', {}).get('node')|default(groups.get('undercloud', {})|first, true)|default(groups.tester, true) }}"
          groups: "tester"
    - include_role:
          name: inventory-update
      vars:
          inventory_file_name: 'hosts-test'


- name: add hosts to run the code using ansible-playbook
  hosts: localhost
  gather_facts: no
  tasks:
     - name: add the patcher host to the tester group
       add_host:
          name: "patcher"
          groups: "tester"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Patch and repackage components RPM
  hosts: "{{ install.pattern | default('tester') }}"
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: copy_component }
    - { role: patch_rpm }

- name: Create tmp directory on a local node and copy RPMs
  hosts: localhost
  tasks:
    - name: Create tmp dir
      tempfile:
        state: directory
        suffix: "{{ ansible_date_time.iso8601 }}"
      register: tempdir_1
      when: "'undercloud' not in groups['tester'][0]"

- name: Copy RPMs
  hosts: "{{ install.pattern | default('tester') }}"
  tasks:
    - name: Copy RPMs using rsync
      synchronize:
        src: "/patched_rpms/"
        dest: "{{ hostvars['localhost']['tempdir_1'].path }}/"
        mode: pull
      when: "'undercloud' not in groups['tester'][0]"

- name: Update undercloud node
  hosts: tester
  become: yes
  tasks:
    - name: Copy RPMs to the undercloud
      block:
        - name: Setup repository in /etc/yum.repos.d
          template:
            src='patched_rpms.j2'
            dest='/etc/yum.repos.d/patched_rpms.repo'
          tags: patched-rpms-repo

        - name: Copy RPMs to the undercloud if created on an another node
          synchronize:
            src: "{{ hostvars['localhost']['tempdir_1'].path }}/"
            dest: "/patched_rpms"
            mode: push
      when: "'undercloud' not in groups['tester'][0]"

- name: Cleanup
  hosts: localhost
  tasks:
    - name: remove the temporary dir
      file:
        path: "{{ tempdir_1.path }}"
        state: absent
      when:
        - tempdir_1.path is defined
        - "'undercloud' not in groups['tester'][0]"
