---
- name: add hosts to host list
  hosts: localhost
  gather_facts: no
  tasks:
     - name: add each host
       add_host:
          name: "tester"
          groups: "undercloud"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)

- name: Patch and repackage components RPM
  hosts: undercloud:tester
  roles:
    - { role: setup_repos }
    - { role: setup_environment}
    - { role: copy_component }
    - { role: patch_rpm }
