---
- name: add hosts to host list
  hosts: localhost
  gather_facts: no
  tasks:
     - add_host:
          name: "controller-0"
          groups: "undercloud"
          ansible_ssh_user: "{{ install.host.username }}"
          ansible_ssh_host: "{{ install.host.ip }}"
          ansible_ssh_private_key_file: "{{ install.host.key_file }}"
       when: (install.host is defined) and (install.host.ip is defined) and (install.host.username is defined) and (install.host.key_file is defined)


- name: Patch and repackage components RPM
  hosts: undercloud
  roles:
    - { role: setup_repos }
    - { role: setup_environment, when: not install.ovs.build|default('') }
    - { role: patch_rpm, when: not install.ovs.build|default('') }
    - { role: build_ovs, when: install.ovs.build|default('') }
