install:
  component:
     name: cinder
     version: 9
#install:
#  host:
#    name: localhost
#    ip:  localhost
#    username: dsariel
#    key_file: 

install:
  host:
    name: undercloud
    ip: 10.8.181.173
    username: cloud-user
    key_file: /home/rhos-ci/.ssh/rhos-jenkins/id_rsa

