- name: load opendaylight variables
  include_vars:
      file: "vars/opendaylight.yml"
      name: opendaylight_vars_all
  tags: odl-package-rpm

- name: "set opendaylight OSP{{ install.component.version }} specific facts"
  set_fact:
      opendaylight_vars: "{{ opendaylight_vars_all[install.component.version | int] }}"
  tags: odl-package-rpm

- name: recreate /tmp/patched required by maven-chain-builder
  file:
      path: '/tmp/patched'
      state: "{{ item }}"
  with_items:
    - absent
    - directory

- name: copy component to /tmp/patched
  command: "cp -pr {{ tmp_dir }}/{{ install.component.name }} /tmp/patched/"
  tags: skip_ansible_lint

- name: Add dummy entries to /etc/hosts file to prevent communication with upstream
  lineinfile:
      dest="/etc/hosts"
      insertafter=EOF
      line="{{ item }}"
  with_items:
      - '127.1.0.1   nexus.opendaylight.org'
      - '127.1.0.2   repo.maven.apache.org'
      - '127.1.0.3   oss.sonatype.org'
      - '127.1.0.4   registry.npmjs.org'

- name: enable rhelosp-rhel..rhscl repo to install maven from
  shell: "yum-config-manager --enable rhelosp-rhel-{{ ansible_distribution_major_version }}-rhscl"
  tags: skip_ansible_lint
  when: install.component.version == 12

- name: enable rhos-odl-rhel-build repo to install maven from
  template:
      src: "rhos-odl-rhel-build.repo.j2"
      dest: "/etc/yum.repos.d/rhos-{{ install.component.version }}.0-odl-rhel-{{ ansible_distribution_major_version }}-build.repo"
  tags: skip_ansible_lint
  when: install.component.version >= 13

- name: Install deps RPMs required for the build
  yum:
      name: "{{ item }}"
      state: present
  with_items: "{{ opendaylight_vars.yum_deps }}"

- name: UnInstall any maven currently installed to avoid packages conflicts
  yum:
      name: maven
      state: absent
  when: install.component.version >= 13

- name: Remove old mvn binaries
  shell: "rm -f /usr/bin/mvn*"
  when: install.component.version == 12
  tags: skip_ansible_lint

- name: symlink java to latest jre
  file:
      path: /usr/lib/jvm/java
      src: /usr/lib/jvm/jre
      state: link
  become: true
  when: install.component.version >= 13

- name: discover maven_home
  shell: "mvn --version | awk '$0 ~ /Maven home:/ {print $3}'"
  register: _maven_home

- name: set maven_home fact
  set_fact:
      maven_home: "{{ _maven_home.stdout }}"

- name: Make maven (mvn) available in $PATH
  shell: "ln -s {{ maven_home }}/usr/bin/* /usr/bin/"
  ignore_errors: no
  when: install.component.version == 12
  tags: skip_ansible_lint

- name: Install Maven PME
  shell: |
      wget {{ opendaylight_vars.pme_url }} -P {{ maven_home }}/lib/ext/
  tags: skip_ansible_lint
  when: install.component.version == 12

- name: set maven m2_settings fact
  set_fact:
      m2_settings_file: "{{ maven_home }}{{ opendaylight_vars.m2_settings_file_path }}"

- name: Install m2 settings (OSP12)
  command: "cp {{ tmp_dir }}/dist-git/{{ component_dist_git_name }}/scripts/config/settings.xml.mead {{ m2_settings_file }}"
  tags: skip_ansible_lint
  when: install.component.version == 12

- name: Install m2 settings (OSP13+)
  get_url:
      dest: "{{ m2_settings_file }}"
      url: "http://git.app.eng.bos.redhat.com/git/odl-odlparent.git/plain/settings.xml?h=rhos-{{ install.component.version }}.0-patches"
      force: yes
      validate_certs: no
      timeout: 30
  tags: skip_ansible_lint
  when: install.component.version >= 13

- name: replace references to upstream nexus with url of downstream mead in m2 settings file
  replace:
      path: "{{ m2_settings_file }}"
      regexp: '<url.*nexus.opendaylight.*'
      replace:  "<url>http://download.devel.redhat.com/brewroot/repos/rhos-{{ install.component.version }}.0-odl-rhel-{{ ansible_distribution_major_version }}-build/latest/maven/</url>"
      backup: yes

- name: disable 'snapshots' profile in m2 settings - https://bugs.eclipse.org/bugs/show_bug.cgi?id=507612
  replace:
      path: "{{ m2_settings_file }}"
      regexp: '(<activeProfile>opendaylight-snapshots</activeProfile>$)'
      replace: '<!-- \1 -->'
      backup: yes

- name: use a load balancer address of download.eng.* to pickup the closest location automagically
  replace:
      path: "{{ m2_settings_file }}"
      regexp: 'download.eng.*.redhat.com'
      replace: 'download.engineering.redhat.com'

- name: remove maven-chain-builder directory
  file:
      path: '{{ tmp_dir }}/maven-chain-builder'
      state: absent

- name: Clone maven-chain-builder
  git:
      repo: https://github.com/wznoinsk/maven-chain-builder.git
      dest: '{{ tmp_dir }}/maven-chain-builder'
      accept_hostkey: true
      version: master

- name: Prepare chain file
  args:
      chdir: "{{ tmp_dir}}/dist-git/opendaylight"
  shell: |
      git config --system http.sslverify false
      # sed -i "s/\$TAG_TO_BUILD/rhos-{{ install.component.version}}.0-patches/g" {{ tmp_dir}}/dist-git/opendaylight/make-vars
      # {{ tmp_dir}}/dist-git/opendaylight/make-vars
      make respin
      cp opendaylight-chain/opendaylight-chain.ini {{ tmp_dir}}/maven-chain-builder/
      git checkout -- make-vars && git checkout -- opendaylight-chain/opendaylight-chain.ini
  tags: skip_ansible_lint

- name: Run maven-chain-builder to build the opendaylight karaf distribution (logs in /var/log/maven/)
  args:
      chdir: "{{ tmp_dir }}/maven-chain-builder"
  shell: "python maven-chain-builder.py opendaylight-chain.ini {{ install.component.name }}"
  register: build_opendaylight
  until: build_opendaylight.rc == 0
  # it may fail because of MEAD server not responding on time, we'll retry a couple of times
  retries: 10
  delay: 10
  # we don't want to fail here to be able to collect logs
  ignore_errors: true
  tags:
      - build-opendaylight
      - skip_ansible_lint

- name: set karaf distribution tar.gz fact - the original package name
  register: odl_karaf_package_fullpath
  shell: find /tmp/org/opendaylight/netvirt -name "{{ opendaylight_vars.karaf_tgz_regex }}" | head -1
  tags:
      - odl-package-rpm
      - skip_ansible_lint

- name: set parent dir fact of the original karaf distribution
  set_fact:
      odl_karaf_package_basename: "{{ odl_karaf_package_fullpath.stdout | basename }}"
  tags: odl-package-rpm

- name: Clone "integration-packaging" required to package OpenDaylight karaf distro into RPM
  git:
      repo: 'https://github.com/wznoinsk/integration-packaging'
      dest: "{{ tmp_dir }}/integration-packaging"
      version: 'master'
      accept_hostkey: yes
  tags:
      - integration-packaging
      - odl-package-rpm

- name: create logs directory for OpenDaylight patching and RPM building
  file:
      path: "{{ tmp_dir }}/integration-packaging/logs"
      state: "{{ item }}"
  with_items:
      - absent
      - directory
  tags: odl-package-rpm

- name: Package OpenDaylight into RPM
  shell: |
      set -e
      rm -rf {{ tmp_dir }}/integration-packaging/packages/cache/*
      rm -f {{ tmp_dir }}/integration-packaging/packages/Dockerfile
      cd {{ tmp_dir }}/integration-packaging/packages/rpm
      ln -s rpm/Dockerfile ../Dockerfile && cd ..
      sudo setenforce 0
      sudo systemctl restart docker

      docker build -t "odl_rpm" . | tee {{ tmp_dir }}/integration-packaging/logs/integration-packaging_docker-build-odl_rpm.log 2>&1

      cp {{ odl_karaf_package_fullpath.stdout }} .
      cp {{ tmp_dir }}/dist-git/opendaylight/opendaylight.service .

      docker run \
      {% if install.component.version >= 13 -%}
      -v {{ tmp_dir }}/dist-git/opendaylight:/dist-git \
      {%- endif %}
      -v $(pwd):/build \
      -v {{ tmp_dir }}:{{ tmp_dir }} \
      odl_rpm \
      --rpm direct \
      --pkg_version 99.commit.{{ component_patch_commitid.stdout }} \
      --pkg_distro el7ost \
      --download_url /build/{{ odl_karaf_package_basename }} \
      --spec_template_path {{ tmp_dir }}/dist-git/opendaylight/opendaylight.spec.tmpl \
      --spec_template_type cheetah \
      --distro_name_prefix {{ opendaylight_vars.distro_name_prefix }} \
      --keep_distro_name True \
      --service_file_url /build/opendaylight.service \
      --keep_service_file_name True \
      {% if install.component.version >= 13 %}
      --extra_src_files /dist-git/monitor.py \
      {%- endif %}
      | tee {{ tmp_dir }}/integration-packaging/logs/integration-packaging_docker-run-odl_rpm.log 2>&1
  register: patch_opendaylight
  # we don't want to fail here to be able to collect logs
  ignore_errors: true
  tags:
      - odl-package-rpm
      - skip_ansible_lint

- name: Save patching logs - OpenDaylight
  become: yes
  shell: |
      cp {{ tmp_dir }}/integration-packaging/logs/* {{ logdir }}
      cp /var/log/maven/* {{ logdir }}
  changed_when: true
  ignore_errors: true
  tags: logs

- name: Remove dummy entries from /etc/hosts preventing communication with upstream
  lineinfile:
      dest="/etc/hosts"
      state=absent
      line="{{ item }}"
  with_items:
      - '127.1.0.1   nexus.opendaylight.org'
      - '127.1.0.2   repo.maven.apache.org'
      - '127.1.0.3   oss.sonatype.org'
      - '127.1.0.4   registry.npmjs.org'

- name: fail if patching was not successful
  fail:
      msg: "OpenDaylight patching not successful, check {{ logdir }}"
  when: patch_opendaylight is not defined or patch_opendaylight.rc != 0

# Create directory to hold the RPMs only if patching successful
- name: "Create '{{ patchedrpmdir }}' directory"
  become: yes
  file:
      path="{{ patchedrpmdir }}"
      state="{{ item }}"
      mode=0777
  with_items:
      - absent
      - directory
  tags: patched-rpms-repo

- name: Copy new generated RPMs to /patched_rpms - OpenDaylight
  shell: "cp {{ tmp_dir }}/integration-packaging/packages/cache/*.noarch.rpm /patched_rpms/"
  tags:
      - patched-rpms-repo
      - skip_ansible_lint
