---
- name: RHEL7 specific repositories
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' | default(false)
  tags:
    - skip_ansible_lint
  block:
    - name: Install rhpkg repos for RHEL-7
      become: yes
      yum_repository:
        name: rhpkg
        state: absent

- name: RHEL8 specific repositories
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8' | default(false)
  tags:
    - skip_ansible_lint
  block:
    - name: Install rhpkg repos for RHEL-8
      become: yes
      yum_repository:
        name: rhpkg
        state: absent

- name: Remove RPMs used for patching
  become: yes
  yum:
    name:
      - rpm-build
      - createrepo
    state: absent
